### ISSUE TITLE
runtime error on Ubuntu 16.04

### ISSUE THREAD

**Issue by BitFis** [darkdragon-001/offlinefs#4] opened 2017-11-14 09:38 UTC
Environment:
```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Commands run:
```bash
> sudo apt-get install libfuse-dev pkg-config libtool automake autoconf g++ libattr1-dev attr libconfuse-dev libdbus-1-dev

> libtoolize
> aclocal
> autoheader
> automake --add-missing
> autoconf
> ./configure
> make
> sudo make install
```
no errors during compilation, but when trying to mount a local file when having two folders - _/tmp/test_ | _/tmp/target_:
```bash
> sudo mount -t ofs file://tmp/test /tmp/target

/sbin/mount.ofs: error while loading shared libraries: libofshash.so.0: cannot open shared object file: No such file or directory
```

Thankyou for your help.

Regards

**Comment by darkdragon-001** [comment] 2017-11-14 19:34
The problem is that the linker cache is not automatically updated. There is a discussion on the libtool mailing list \[[1](http://lists.gnu.org/archive/html/libtool/2014-05/msg00021.html), [2](http://lists.gnu.org/archive/html/libtool/2017-11/msg00000.html)\] about this topic. I will leave this issue open until this is fixed.

As a temporary fix, one can run `sudo ldconfig` after the build.

**Comment by BitFis** [comment] 2017-11-21 08:58
seems to work, but now when trying to mount getting following error:
```bash
> sudo mount -t ofs file://mnt/xtreemfs/globalshare /mnt/globalshare

terminate called after throwing an instance of 'OFSException'
  what():  Failed to create /usr/local/var/ofs/backing/o2GwJ1Ap_LLu5KwY9RIJ0mpjh1o
```

folder _mnt/xtreemfs/globalshare_ is a normal file, so no mount. Maybe I am missing something.

**Comment by darkdragon-001** [comment] 2017-11-21 15:40
It works to mount a folder for me. Mounting a single file does not work though...

**Comment by BitFis** [comment] 2017-11-21 20:09
Sry, can't get it to work on `Linux xxxxxxxxx 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by darkdragon-001** [comment] 2017-11-23 12:02
I use Ubuntu 17.10: `Linux xxxxx 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`. But it worked already with way older kernels.

Can you try to do a fresh clone and then fresh installation according to the instructions in the readme?

**Comment by darkdragon-001** [comment] 2022-01-15 18:25
I tried it again on Ubuntu 21.10 and it still works for me. Closing for now. Please re-open if you can reproduce or provide more information.

**Closed as completed by darkdragon-001** 2022-01-15 18:25 UTC
